language: go

go:
  - 1.2
  - 1.3
  - 1.4
  - tip

before_install:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - $HOME/gopath/bin/goveralls -repotoken woItNGBMB0m954phEISoUSa4qgNDTD7D2
